### PR TITLE
Adds mod count player and fixes time elapsed calculation

### LINKED ISSUE #24: New player: modcount
A player with the solution `[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, ...]`

### PR DESCRIPTION
**Pull request by jovobe**
fixes #24 #22

### CODE REVIEW

File: drencher/src/solver/mod_count.rs [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+            let color = Color::new(index);
+            solution.push(color);
+            b.drench(color);
+
+            index += 1;
+            index %= 6;
+        }
+
+        Ok(solution)
+    }
```
Comment (LukasKalbertodt) [inline drencher/src/solver/mod_count.rs:24]: Let's make it more functional and rusty! How about:

``` rust
Ok(
    (0..)
        .map(|i| Color::new(i % 6))
        .take_while(|_| !b.is_drenched())
        .inspect(|&c| b.drench(c))
        .collect()
)
```

Just wrote it, not entirely sure if it works...

**Comment by jovobe** [comment]
Updated PR @LukasKalbertodt
